from django.urls import path
from . import views

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.welcome, name='user-welcome'),
    path('base/', views.base, name='user-base'),
    path('default_home_base/', views.default_home_base, name='user-default_home_base'),
    path('admin_or_user/', views.admin_or_user, name='admin_or_user'),
    path('default_home/', views.default_home, name='user-default_home'),
    path('register/', views.register, name='user-register'),
    path('log_out/', views.log_out, name='user-log_out'), 
    path('log_in/', views.log_in, name='user-log_in'), 
    path('update_success/', views.update_success, name='user-update_success'),
    path('registration_success/', views.registration_success, name='user-registration_success'),
    path('edit_profile/', views.edit_profile, name='user-edit_profile'),
    path('password/', views.change_password, name='user-password'),
    path('add_professor/', views.add_professor, name='user-add_professor'),
    path('show_professor_list/', views.show_professor_list, name='user-show_professor_list'), 
    path('update_professor/<professor_id>/<address_id>/<departmant_id>/<academic_degree_id>/<theses_id>/', views.update_professor, name='user-update_professor'), 
    path('add_scientificJournal/', views.add_scientificJournal, name='user-add_scientificJournal'),
    path('show_scientificJournal_list/', views.show_scientificJournal_list, name='user-show_scientificJournal_list'), 
    path('update_scientificJournal/<scientificJournal_id>', views.update_scientificJournal, name='user-update_scientificJournal'),  
    path('add_collection/', views.add_collection, name='user-add_collection'),
    path('show_collection_list/', views.show_collection_list, name='user-show_collection_list'), 
    path('update_collection/<collection_id>', views.update_collection, name='user-update_collection'), 
    path('add_conference_participation/', views.add_conference_participation, name='user-add_conference_participation'),
    path('show_conference_participation_list/', views.show_conference_participation_list, name='user-show_conference_participation_list'), 
    path('update_conference_participation/<conference_participation_id>', views.update_conference_participation, name='user-update_conference_participation'),
    path('add_patent/', views.add_patent, name='user-add_patent'),
    path('show_patent_list/', views.show_patent_list, name='user-show_patent_list'), 
    path('update_patent/<patent_id>', views.update_patent, name='user-update_patent'), 
    path('add_dissertation_leading/', views.add_dissertation_leading, name='user-add_dissertation_leading'),
    path('show_dissertation_leading_list/', views.show_dissertation_leading_list, name='user-show_dissertation_leading_list'), 
    path('update_dissertation_leading/<dissertation_leading_id>', views.update_dissertation_leading, name='user-update_dissertation_leading'),
    path('add_grant/', views.add_grant, name='user-add_grant'),
    path('show_grant_list/', views.show_grant_list, name='user-show_grant_list'), 
    path('update_grant/<grant_id>', views.update_grant, name='user-update_grant'), 
    path('add_prize/', views.add_prize, name='user-add_prize'),
    path('show_prize_list/', views.show_prize_list, name='user-show_prize_list'), 
    path('update_prize/<prize_id>', views.update_prize, name='user-update_prize'), 
    path('add_education/', views.add_education, name='user-add_education'),
    path('show_education_list/', views.show_education_list, name='user-show_education_list'), 
    path('update_education/<education_id>', views.update_education, name='user-update_education'), 
]